apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados
  labels:
    type: local
spec:
  storageClassName: manual #vincula o claim com PV
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce #gravação e execução
  hostPath: 
    path: /meubanco/