apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cloud
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: pvc-cloud
          mountPath: /var/lib/mysql  #referência no contêiner
      
      volumes:
      - name: pvc-cloud
        persistentVolumeClaim:
          claimName: pvc-cloud
        