apiVersion: v1
kind: Pod
metadata:
  name: app-html
  labels:
    name: app-html
spec:
#Informação dos containeres
  containers:
  - name: app-html
    image: httpd:latest
    ports:
      - containerPort: 80
